add ssc policy

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -36,4 +36,17 @@ jobs:
           name: Semgrep diff scan
           environment: 
             SEMGREP_BASELINE_REF: << parameters.default_branch >>
-          command: semgrep ci
+          command: |
+              semgrep ci --json --output report-ssc.json
+              json_file=report-ssc.json
+              findings=$(jq -r '.results[]' "$json_file")
+              for k in $(jq '.results | keys | .[]' "$json_file"); do
+                  value=$(jq -r ".results[$k]" "$json_file");
+                  severity=$(jq -r '.extra.severity' <<< "$value");
+                  reachable=$(jq -r '.extra.sca_info.reachable' <<< "$value");
+                  if [[ $severity == "ERROR" && $reachable == "true" ]]; then
+                      echo "Exiting with error code 1"
+                      exit 1;
+                  fi
+              done
+
